In [1]:
import pandas as pd

In [2]:
worker_order_df = pd.read_csv('workorderdata/workorderdata.csv')

/Users/einar/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (43,46,48,49,52,53,54) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

## Facts

In [3]:
worker_order_df.drop(['DaysLeftForSchCompliance', 'DaysLeftForPM', 'SystemStatus'], axis=1, inplace=True)

## Assumptions

In [4]:
worker_order_df.drop(['(No column name)',
                      'StatusShortDescription',
                      'EquipmentDescription',
                      # 'Model',
                      'EquipmentRollupCode',
                      # 'PMOriginalDueDate',
                      # 'PMOverdue'
                     ], axis=1, inplace=True)

## Clean up

In [5]:
d = {"type": worker_order_df.dtypes,
     "NaN" : worker_order_df.isna().sum(),
    }
df = pd.DataFrame(d).sort_values(by=['NaN'])
df

                          type      NaN
WorkOrder               object        0
SupervisorRole          object        0
TradeGroup              object        0
CreatedDate             object        0
IsAffectingProduction   object        0
AffectedProduction       int64        0
GrossProductionLoss      int64        0
Duration                 int64        0
Safety                  object        0
WOType                  object        0
Reopened                object        0
StatusDescription       object        0
EquipmentCode           object        0
StatusCode              object        0
EquipmentType           object        0
FieldProductionTeam     object     1244
EquipmentClass          object     9402
SchEndDate              object    12234
EquipmentCriticality    object    21500
Area                    object    27486
ReportDate              object    59178
CreatedBy               object    72794
Manufacturer            object   115909
CompletedDate           object   139647
JobType                 object   198003
Priority               float64   198997
UpdatedDate             object   219556
Model                   object   219752
UpdatedBy               object   246989
FieldOperationsTeam     object   277885
Action                  object   347403
Assigned                object   391923
Trade                   object   391923
MaterialCost           float64   601936
LaborCost              float64   601936
TotalCost              float64   601936
ActualDuration         float64   709910
ScheduleCompliant       object   709910
ScheduleWindowEnd       object   710262
TargetDate              object   710262
ScheduleWindowStart     object   710262
CompletedWeek           object   710815
Requirement             object   861848
FailureReason           object   865993
Cause                   object   868927
EquipmentDown           object   948639
PMOriginalDueDate       object  1079342
PMOverdue               object  1098290